### PR TITLE
Cleanup, as per #1

### PR DESCRIPTION
**Pull request by ivmarkov**
This PR is a major cleanup (sorry!). It solves the following issues:
* `cargo fmt`
* `app` and `host` folders' copy-paste from the rustzx app removed
* Requirements on SPI RAM removed
* More LED boards supported

What would be the major next steps if this emulator is to work properly?
* Most important is to **optimize the emulator itself**. I've configured it to run with 60 frames full-speed without interruption, and the result is that these 60 frames take ~ 8.5 seconds to render so we get ~ 7fps, while we should get 30-50fps to have a chance for a smooth playback (note that the SPI/display speed is not a major contributor - it is the emulator itself; even if you comment out the `set_pixel` code completely, it still runs with ~ 7fps)

So... either we optimize the emulator itself, or well, we stop here. :)

### CODE REVIEW

**Comment by georgik** [comment]
Thank you very much @ivmarkov . That's pretty amazing.
Please, could you provide me a hint how to build the main branch?
When I try this (build for USB OTG with S2 - compatible with S3):
```
cargo +esp-1.56.0.1 build --target xtensa-esp32s2-espidf --release --features "esp32s3_usb_otg native"
```


The build fails with:
```
error: The `ttgo` feature can only be built for the `xtensa-esp32-espidf` target.
  --> src\display.rs:14:1
   |
14 | compile_error!("The `ttgo` feature can only be built for the `xtensa-esp32-espidf` target.");
   | ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

error: The `esp32s3_usb_otg` feature can only be built for the `xtensa-esp32s3-espidf` target.
  --> src\display.rs:20:1
   |
20 | / compile_error!(
21 | |     "The `esp32s3_usb_otg` feature can only be built for the `xtensa-esp32s3-espidf` target."
22 | | );
   | |__^

error[E0412]: cannot find type `Gpio23` in module `gpio`
   --> src\display.rs:120:16
    |
120 |     rst: gpio::Gpio23<gpio::Unknown>,
    |                ^^^^^^ help: a struct with a similar name exists: `Gpio13`
    |
   ::: C:\Users\JurajMichálek\.cargo\registry\src\github.com-1ecc6299db9ec823\esp-idf-hal-0.24.0\src\gpio.rs:738:5
    |
738 |     pin!(Gpio13:13, IO, RTC:13, ADC2:2, NODAC:0, TOUCH:13);
    |     ------------------------------------------------------- similarly named struct `Gpio13` defined here

error[E0412]: cannot find type `Gpio23` in module `gpio`
   --> src\display.rs:137:15
    |
137 |         gpio::Gpio23<gpio::Output>,
    |               ^^^^^^ help: a struct with a similar name exists: `Gpio13`
    |
   ::: C:\Users\JurajMichálek\.cargo\registry\src\github.com-1ecc6299db9ec823\esp-idf-hal-0.24.0\src\gpio.rs:738:5
    |
738 |     pin!(Gpio13:13, IO, RTC:13, ADC2:2, NODAC:0, TOUCH:13);
    |     ------------------------------------------------------- similarly named struct `Gpio13` defined here

warning: unused import: `thread`
 --> src\main.rs:3:11
  |
3 | use std::{thread, time::*};
  |           ^^^^^^
  |
  = note: `#[warn(unused_imports)]` on by default


error[E0609]: no field `gpio23` on type `esp_idf_hal::gpio::Pins`
  --> src\display.rs:62:31
   |
62 |             $peripherals.pins.gpio23,
   |                               ^^^^^^ help: a field with a similar name exists: `gpio2`
   |
  ::: src\main.rs:35:16
   |
35 |     emulate_zx(display::create!(peripherals)?, display::color_conv)
   |                ----------------------------- in this macro invocation
   |
   = note: this error originates in the macro `display::create` (in Nightly builds, run with -Z macro-backtrace for more info)

error[E0308]: mismatched types
  --> src\display.rs:82:13
   |
82 |             $peripherals.spi2,
   |             ^^^^^^^^^^^^^^^^^ expected struct `SPI3`, found struct `SPI2`
   |
  ::: src\main.rs:35:16
   |
35 |     emulate_zx(display::create!(peripherals)?, display::color_conv)
   |                ----------------------------- in this macro invocation
  
   ```

**Comment by ivmarkov** [comment]
Feature `ttgo` was in the default features. If you re-pull my main, or the PR branch, your build should work.

**Comment by ivmarkov** [comment]
If it still fails, let me know, and I'll check the pin layout for your card, as I could've messed it up a bit... :)

**Comment by ivmarkov** [comment]
Pin layout is OK, it should build.

**Comment by ivmarkov** [comment]
Huh wait. Why are you building for the `esp32s2` target? Is this card an `esp32s2` one, or an `esp32s3` one?

**Comment by georgik** [comment]
It's because USB OTG board in the preview version was shipped with S2. The mass production version is now on S3.
The HW that I had available was on S2. 

Nevertheless I've grabbed S3 version which is available at espressif.com, so that we avoid this confusion.

**Comment by ivmarkov** [comment]
> It's because USB OTG board in the preview version was shipped with S2. The mass production version is now on S3. The HW that I had available was on S2.
> 
> Nevertheless I've grabbed S3 version which is available at espressif.com, so that we avoid this confusion.

Supporting both is not a rocket science, I pushed that.

**Comment by georgik** [comment]
Thank you @ivmarkov .

Is there a reason for SPI2 in display configuration?

The build for USB OTG on S2 fails with:
```
error[E0308]: mismatched types
  --> src\display.rs:88:13
   |
88 |             $peripherals.spi2,
   |             ^^^^^^^^^^^^^^^^^ expected struct `SPI3`, found struct `SPI2`
```
After changing to SPI3 the build is passing without problem.

**Comment by ivmarkov** [comment]
No, that's a bug. Changed to SPI3.

**Comment by georgik** [comment]
Validated with USB OTG S2 - the solution works.
@ivmarkov Thank you very much for clean up and great improvements.

**Pull request merged**
